project:
  type: website
  output-dir: docs

website:
  title: "Gapminder Mini-Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: life-gdp.qmd
        text: Life Expectancy and GDP per Capita
      - href: life-population.qmd
        text: Life Expectancy and Population
      - href: country.qmd
        text: Country Analysis

format:
  html:
    theme: cosmo
    toc: true
    self-contained: false

execute:
  echo: true
  warning: false
  message: false
